### ISSUE TITLE
remove disabled tests when wait_for_service support is added to fastrtps

### ISSUE THREAD

**Issue by wjwwood** [ros2/examples#113]
See: https://github.com/ros2/ros2/issues/215#issuecomment-226589984

Links:

- https://github.com/ros2/examples/commit/b22dda0bb04b8d61952494e4e705d1b6af56399b#diff-3a0a0c56f3d14a51b5ffb0d630b46d1fR78

**Comment by wjwwood** [comment]
Tracked: https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/issues/14

**Comment by dirk-thomas** [comment]
Is #120 covering this ticket or are there any more tests to be reenabled?

**Comment by wjwwood** [comment]
I just double checked this and I believe it can be closed. Thanks for following up on it.
