### ISSUE TITLE
problems about code style in ros2

### ISSUE THREAD

**Issue by lxbeyond** [ros2/examples#201]
I have test rclpy program in examples reps, and I'm confused about the comments "We do not recommend this style as ROS 2 provides timers for this purpose, and it is recommended that all nodes call a variation of spin." int file  examples/rclpy/topics/minimal_publisher/publisher_local_function.py . Is it just a code style problem or that this will make difference to the performance of program ? I used to work in ros1, and familiar to the code style in  file "publisher_local_function.py", need I change the code style ?

**Comment by sloretz** [comment]
It affects the performance of programs that use callbacks. I think you are referring to this warning in `publisher_old_school.py`. The style in `publisher_local_function.py` or `publisher_member_function.py` is preferred.

https://github.com/ros2/examples/blob/a75151ef1388b565268508228df42c06462c1337/rclpy/topics/minimal_publisher/publisher_old_school.py#L21-L24

The example has one thread (main thread), and it is blocked when the loop calls `time.sleep(0.5)`. There would be a problem in ros2 if the example also had a subscriber.

https://github.com/ros2/examples/blob/a75151ef1388b565268508228df42c06462c1337/rclpy/topics/minimal_publisher/publisher_old_school.py#L36-L42

In ros1 (rospy) each subscribed topic is given its own thread. When a subscriber receives a message the subscriber's callback is called regardless of whether or not the main thread is sleeping.

In ros2 (rclpy) the user has more control of the threading model. All callbacks are called via an `Executor`, and as a consequence callbacks are only called when the executor is spinning. Even if a subscriber received a message the users' subscription callback would never be called during that loop.
