### ISSUE TITLE
100% action server CPU usage when cancelling a goal from the client

### ISSUE THREAD

**Issue by jubeira** [ros2/examples#221]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Bionic 18.04 (as in [Nvidia OpenGL Docker image](https://hub.docker.com/r/nvidia/opengl/))
- Installation type:
  - Binaries
- Version or commit hash:
  - Crystal pre-release (updated 14-12-2018; version 0.6.1)
- DDS implementation:
  - Checked with FastRTPS and `connext_cpp`
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
Start `top` in a terminal to monitor CPU usage.

Then, from another terminal, run `minimal_action_server`:
```
ros2 run examples_rclcpp_minimal_action_server action_server_not_composable
```
Finally, run `minimal_action_client` with cancel:
```
ros2 run examples_rclcpp_minimal_action_client action_client_not_composable_with_cancel
```

#### Expected behavior
Action is canceled, everything exits gracefully.
#### Actual behavior
Action is canceled, but in some cases a CPU thread keeps working at 100% until the server is shut down.
#### Additional information
This doesn't happen _every time_ the action client is launched, but it's not too hard to reproduce either by launching it a few times. It seems to happen ~50% of the times.
This might be related to https://github.com/ros2/rcl/issues/354.

**Comment by sloretz** [comment]
I can reproduce this on arm64 using https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/650/ .

It doesn't appear to be related to cancellation. It also happens with the non-cancel example.

```
ros2 run examples_rclcpp_minimal_action_client action_client_not_composable
```

The 100% CPU usage starts as soon as the goal request is sent. It can be caused by calling the service directly

```
ros2 service call /fibonacci/_action/send_goal example_interfaces/Fibonacci_Goal "{order: 1, action_goal_id: {uuid: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]}}"
```
