### ISSUE TITLE
Action client examples not working with CycloneDDS

### ISSUE THREAD

**Issue by hidmic** [ros2/examples#257]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04, both AMD64 and ARM64
- Installation type:
  - Binaries and from source
- Version or commit hash:
  - https://github.com/ros2/examples/commit/dad93c3e81043be5c11194371dafe7affb7a527d (ROS 2 workspace at [this ros2.repos](https://github.com/ros2/ros2/blob/a326ca46d03c9db647dad5583b92a0ed52ca466f/ros2.repos))
- DDS implementation:
  - CycloneDDS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

1. On one terminal, run:

```console
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 run examples_rclcpp_minimal_action_server action_server_not_composable
```

2. On another terminal, run:

```console
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 run examples_rclcpp_minimal_action_client action_client_not_composable
```

#### Expected behavior
Action client sends goal to the action server, receives feedback and result, and finally self terminates.

#### Actual behavior
Action client hangs right after sending the goal.

#### Additional information
Action clients seem to be blocking forever at [rclcpp::spin_until_future_complete()](https://github.com/ros2/examples/blob/dad93c3e81043be5c11194371dafe7affb7a527d/rclcpp/minimal_action_client/not_composable.cpp#L43).

**Comment by dirk-thomas** [comment]
It works for me using the current Debian packages from the testing repo.

**Comment by hidmic** [comment]
Hmm, I just built everything from source, from scratch, and client examples still hang. Maybe someone else can disambiguate?

**Comment by jacobperron** [comment]
I can reproduce with a from-source build, but it works fine using the Eloquent debs.

**Comment by hidmic** [comment]
Hmm could the difference be due to `CMAKE_BUILD_TYPE=None` vs. `CMAKE_BUILD_TYPE=Release`?

**Comment by dirk-thomas** [comment]
I used `CMAKE_BUILD_TYPE=Debug`.

**Comment by wjwwood** [comment]
Maybe related to https://github.com/ros2/rmw_cyclonedds/issues/74

**Comment by jrgnicho** [comment]
I'm having a similar issue, however I'm calling `future.wait_for(timeout);` from the client after sending the asynchronous goal and it times out even though my server does call the `goal_handle->succeed(...)` function long before the timeout elapses.

**Comment by jrgnicho** [comment]
It looks like in order to prevent the action client (and server) from hanging it's necessary to spawn a multithreaded executor and as many callback groups as there are clients or servers as shown in the [multithreaed executor example](https://github.com/ros2/examples/blob/master/rclcpp/multithreaded_executor/multithreaded_executor.cpp)

**Comment by sloretz** [comment]
I can't reproduce on `master` having built with `CMAKE_BUILD_TYPE=Debug`

```console
$  RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 run examples_rclcpp_minimal_action_server action_server_not_composable
1608681598.423987 [0] action_ser: using network interface enp3s0 (udp/192.168.1.150) selected arbitrarily from: enp3s0, docker0
[INFO] [1608681606.864051515] [server]: Got goal request with order 10
[INFO] [1608681606.864578896] [server]: Executing goal
[INFO] [1608681606.864728112] [server]: Publish Feedback
[INFO] [1608681607.865073088] [server]: Publish Feedback
[INFO] [1608681608.865039250] [server]: Publish Feedback
[INFO] [1608681609.865129641] [server]: Publish Feedback
[INFO] [1608681610.865143539] [server]: Publish Feedback
[INFO] [1608681611.865057456] [server]: Publish Feedback
[INFO] [1608681612.865084460] [server]: Publish Feedback
[INFO] [1608681613.864887598] [server]: Publish Feedback
[INFO] [1608681614.864928344] [server]: Publish Feedback
[INFO] [1608681615.865677314] [server]: Goal Succeeded
```

```console
$ RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 run examples_rclcpp_minimal_action_client action_client_not_composable
1608681606.846930 [0] action_cli: using network interface enp3s0 (udp/192.168.1.150) selected arbitrarily from: enp3s0, docker0
[INFO] [1608681606.863703627] [minimal_action_client]: Sending goal
[INFO] [1608681606.865485261] [minimal_action_client]: Waiting for result
[INFO] [1608681615.866202732] [minimal_action_client]: result received
[INFO] [1608681615.866384170] [minimal_action_client]: 0
[INFO] [1608681615.866477418] [minimal_action_client]: 1
[INFO] [1608681615.866550782] [minimal_action_client]: 1
[INFO] [1608681615.866675816] [minimal_action_client]: 2
[INFO] [1608681615.866756165] [minimal_action_client]: 3
[INFO] [1608681615.866825524] [minimal_action_client]: 5
[INFO] [1608681615.866893118] [minimal_action_client]: 8
[INFO] [1608681615.866962232] [minimal_action_client]: 13
[INFO] [1608681615.867030766] [minimal_action_client]: 21
[INFO] [1608681615.867098315] [minimal_action_client]: 34
[INFO] [1608681615.867165039] [minimal_action_client]: 55
```

**Comment by clalancette** [comment]
I also can't reproduce on the latest (though I don't have a Debug build handy).

@hidmic Can you confirm @sloretz 's findings on the latest, and close this out if appropriate?

**Comment by hidmic** [comment]
Indeed. It works now. Thanks and sorry for the delay!
