### ISSUE TITLE
Goal queuing action server won't allow for cancels

### ISSUE THREAD

**Issue by hidmic** [ros2/examples#271]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Focal 20.04 ARM64 
- Installation type:
  - Binaries
- Version or commit hash:
  - [d51db0c680224c9ad7aeafc04d2cfdffa511c813](https://github.com/ros2/examples/tree/d51db0c680224c9ad7aeafc04d2cfdffa511c813)
- Client library (if applicable):
  - `rclpy`

#### Steps to reproduce issue

Start the server:

```sh
ros2 run examples_rclpy_minimal_action_server server_queue_goals
```

Send a goal and try to cancel, e.g. using:

```sh
ros2 run examples_rclpy_minimal_action_client client_cancel
```

#### Expected behavior
Goal gets accepted and later cancelled when requested.

#### Actual behavior
Goal cannot be cancelled once started.

#### Additional information
The issue here is that this _one goal at a time_ behavior is achieved by means of a single threaded executor. This doesn't allow concurrent goal executions, but it also prevents goal cancel callbacks to be served. It turns out it's not particularly easy to tell `rclpy.action` to defer a goal handle for later execution. CC @jacobperron for valuable input.

**Comment by jacobperron** [comment]
Regarding deferring goals, we have an example where the goal is deferred using a timer: 

https://github.com/ros2/examples/blob/master/rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server_defer.py

Maybe we could do something similar for the goal queuing example; provide an "handle accepted callback" and wait for the current goal to finish before calling `execute()` on the next one. Note, the default handle accepted callback is here:

https://github.com/ros2/rclpy/blob/044ff46603940444432f938df10450bca8d7c4c5/rclpy/rclpy/action/server.py#L176-L178

Maintaining our own list of goals to execute and using a multithreaded executor will make the example a bit more complicated, but it seems necessary to achieve what we want.
