### ISSUE TITLE
Equivalent of following codes in ros2

### ISSUE THREAD

**Issue by addy1997** [ros2/examples#306]
Required Info:

    Operating System:
        Ubuntu 20.04
    Installation type:
        Binaries
    Version or commit hash:
        foxy
    Client library (if applicable):
        rclccp, boost

I am creating a plugin for the "actor" to follow a path using ros2 and ign gazebo. For that, I want to know what is the equivalent of following one-liners in ros2

`ros::NodeHandle * ros_node_;`

`ros::Subscriber state_sub_;`

`ros::CallbackQueue queue_;`

`boost::thread callbackQueueThread_;`

Please can anybody suggest something?

**Comment by clalancette** [comment]
For questions like this, please ask on https://answers.ros.org , where you can get more help.  Also include a lot more information about what you are trying to do.  I'm going to close this for now.
