### ISSUE TITLE
Branch examples for Galactic?

### ISSUE THREAD

**Issue by sloretz** [ros2/examples#311]
@mabelzhang any objections?

This one seems easy. Branching will allow merging breaking changes for Rolling again. The process is to create a new branch `galactic` from `master`, and update `galactic/distribution.yaml` in rosdistro.

**Comment by mabelzhang** [comment]
Sounds good! Looks consistent with previous distros.

**Comment by Aut0R3V** [comment]
@sloretz can I work on this

**Comment by clalancette** [comment]
This was already done, I'll close this out.
