### ISSUE TITLE
ROS 2

### ISSUE THREAD

**Issue by MManojPrabhakar** [ros2/examples#338]
manoj@ade:~/ros2_example_ws$ colcon build --symlink-install

Starting >>> examples_rclcpp_minimal_action_client
Starting >>> examples_rclcpp_minimal_action_server
Starting >>> examples_rclcpp_minimal_client
Starting >>> examples_rclcpp_minimal_composition
Starting >>> examples_rclcpp_minimal_publisher
Starting >>> examples_rclcpp_minimal_service
Starting >>> examples_rclcpp_minimal_subscriber
Starting >>> examples_rclcpp_minimal_timer
--- stderr: examples_rclcpp_minimal_action_server                                                                                                                                             
CMake Error: The source directory "" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [cmake_check_build_system] Error 1
---
Failed   <<< examples_rclcpp_minimal_action_server [0.25s, exited with code 2]
Aborted  <<< examples_rclcpp_minimal_service [0.22s]
Aborted  <<< examples_rclcpp_minimal_client [0.25s]
Aborted  <<< examples_rclcpp_minimal_publisher [0.23s]
Aborted  <<< examples_rclcpp_minimal_action_client [0.28s]
Aborted  <<< examples_rclcpp_minimal_timer [0.21s]
Aborted  <<< examples_rclcpp_minimal_subscriber [0.21s]
Aborted  <<< examples_rclcpp_minimal_composition [0.25s]
                                 
Summary: 0 packages finished [0.53s]
  1 package failed: examples_rclcpp_minimal_action_server
  7 packages aborted: examples_rclcpp_minimal_action_client examples_rclcpp_minimal_client examples_rclcpp_minimal_composition examples_rclcpp_minimal_publisher examples_rclcpp_minimal_service examples_rclcpp_minimal_subscriber examples_rclcpp_minimal_timer
  7 packages had stderr output: examples_rclcpp_minimal_action_client examples_rclcpp_minimal_action_server examples_rclcpp_minimal_client examples_rclcpp_minimal_publisher examples_rclcpp_minimal_service examples_rclcpp_minimal_subscriber examples_rclcpp_minimal_timer
  7 packages not processed

**Comment by clalancette** [comment]
This is a weird error, it looks like something in your setup is not correct.

For questions like this, please use https://answers.ros.org, which is our central question and answers site.  Make sure to provide a lot of detail on how you installed ROS 2, what platform you are on, and all of the commands you are using.  I'm going to close this one out.
