### ISSUE TITLE
build src/ament/uncrustify fails

### ISSUE THREAD

**Issue by spiked3** [ros2/examples#36]
Uncrustify_Win32_2011.vcxproj: The application which this project type is based on was not found.

Looks like project was not migrated?

**Comment by wjwwood** [comment]
@spiked3 Our build script tries to upgrade the project in place, see:

https://github.com/ament/uncrustify/blob/master/CMakeLists.txt#L74-L82

It's not clear to me why you get that message. We've talked about upgrading it and committing the upgrade, but we haven't yet. You can try to open it in VS manually and have it upgrade it, then try again.

Unfortunately, I think you'll run into other issues a little further down the line, it's currently failing on our CI:

http://ci.ros2.org/job/ros2_batch_ci_windows/5/

I haven't gotten around to fixing it this time.

**Comment by spiked3** [comment]
Yeah, it almost look as though 'doesnt need upgrading' is the error that is stopping the build.

I will see if I can figure it out. I (as a windows person) was looking forward to ROS2. Thanks.

**Comment by dirk-thomas** [comment]
Our build farm is able to get beyond that point with the current code base: http://ci.ros2.org/job/ros2_batch_ci_windows/12/

@spiked3 Are you still having this problem or can this be closed?

**Comment by spiked3** [comment]
according to the current status, it is still failing.  But since I was told no one was working on it, I have not really tried since then.  Close it.

**Comment by dirk-thomas** [comment]
The current job fails after `uncrustify` was build successfully at a different package. It would be great if you could confirm that the problem is also solved for you.

**Comment by spiked3** [comment]
I no longer have a lot of the software installed.  I will put this on my ToDo list, but it may be a while.

**Comment by dirk-thomas** [comment]
I will close the ticket for now since it seems to work for us now. But once you had a chance to try it again please comment again to either confirm that its fixed or to reopen the ticket. Thanks.

**Comment by spiked3** [comment]
still fails, same place and message;

       CustomBuild:
         Building Custom Rule C:/dev/ros2/src/ament/uncrustify/CMakeLists.txt
         CMake does not need to re-run because C:\dev\ros2\build\uncrustify\CMa
         keFiles\generate.stamp is up-to-date.
         Generating C:/dev/ros2/src/ament/uncrustify/src/uncrustify_version.h
         Could Not Find C:\dev\ros2\src\ament\uncrustify\src\uncrustify_version
         .h
         Generating C:/dev/ros2/src/ament/uncrustify/win32/Debug/Uncrustify.exe

         Some errors occurred during migration. For more information, see the m
         igration report:
         C:\dev\ros2\src\ament\uncrustify\win32\UpgradeLog.htm

         Information:
         This project/solution does not require migration. It will open without
          modification.
     5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppComm
       on.targets(170,5): error MSB6006: "cmd.exe" exited with code 1. [C:\dev\
       ros2\build\uncrustify\external_uncrustify.vcxproj]
     5>Done Building Project "C:\dev\ros2\build\uncrustify\external_uncrustify.
       vcxproj" (default targets) -- FAILED.
     3>Done Building Project "C:\dev\ros2\build\uncrustify\external_uncrustify.
       vcxproj.metaproj" (default targets) -- FAILED.
     2>Done Building Project "C:\dev\ros2\build\uncrustify\ALL_BUILD.vcxproj.me
       taproj" (default targets) -- FAILED.
     1>Done Building Project "C:\dev\ros2\build\uncrustify\uncrustify.sln" (def
       ault targets) -- FAILED.

Build FAILED.

       "C:\dev\ros2\build\uncrustify\uncrustify.sln" (default target) (1) ->
       "C:\dev\ros2\build\uncrustify\external_uncrustify.vcxproj.metaproj" (def
       ault target) (3) ->
       "C:\dev\ros2\build\uncrustify\external_uncrustify.vcxproj" (default targ
       et) (5) ->
       (CustomBuild target) ->
         C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCo
       mmon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1. [C:\de
       v\ros2\build\uncrustify\external_uncrustify.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.24

<== Command 'C:\dev\ros2\build\uncrustify\cmake__build.bat C:\Program Files (x86
)\MSBuild\14.0\bin\amd64\msbuild.EXE /m C:\dev\ros2\build\uncrustify\uncrustify.
sln' failed with exit code '1'

C:\dev\ros2>

**Comment by dirk-thomas** [comment]
I will reopen the ticket since it still happens for you.
But since it works for us and we don't know a way to reproduce you problem we can't help much in trouble shooting it.

I assume you use the latest state from all repositories as well as Visual Studio 2015. May be it helps if you post more information about your exact environment and versions as well as the command sequence you use.

**Comment by spiked3** [comment]
I am usually up to date on everything and that might be part of the problem. I noticed one of the recommended packages would not install. cppcheck is in a choco 'pending' state so I downloaded the newer .msi and installed manually. Other than that nothing unusual I can think of.

**Comment by dirk-thomas** [comment]
The console output of our CI job (http://ci.ros2.org/job/ros2_batch_ci_windows/13/consoleFull) only indicates warnings during the migration of the project file:

    Migration completed successfully, but some warnings were detected during migration.

while your contains errors:

    Some errors occurred during migration. For more information, see the migration report:
    C:\dev\ros2\src\ament\uncrustify\win32\UpgradeLog.htm

Can you please check the content of that upgrade log.

**Comment by spiked3** [comment]
It points to the generic migration page;  
https://msdn.microsoft.com/en-US/library/hh266747(v=vs.120).aspx

But I notice a comment;
You can use Visual Studio 2013 to open a C++ project that was created in Visual Studio 2012 or Visual Studio 2010 SP1. If you want to use the Visual Studio 2013 build environment to build a project that was created in Visual Studio 2012, you must have both versions of Visual Studio installed on the same computer.

I'm wondering if I would need to have vs2010 installed? (which I do not)

**Comment by dirk-thomas** [comment]
We certainly have only VS 2015 on our build slave.

Is the message you posted a 1-to-1 copy from the upgrade log? If yes, are you using Visual Studio 2013? For our CI job the log looks like this: http://ci.ros2.org/job/ros2_batch_ci_windows/ws/workspace/src/ament/uncrustify/win32/UpgradeLog.htm

**Comment by spiked3** [comment]
<!DOCTYPE html>

 <html xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta content="en-us" http-equiv="Content-Language" /><meta content="text/html; charset=utf-16" http-equiv="Content-Type" /><title _locID="ConversionReport0">
          Migration Report
        </title><style> 
                    /* Body style, for the entire document */
                    body
                    {
                        background: #F3F3F4;
                        color: #1E1E1F;
                        font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
                        padding: 0;
                        margin: 0;
                    }

                    /* Header1 style, used for the main title */
                    h1
                    {
                        padding: 10px 0px 10px 10px;
                        font-size: 21pt;
                        background-color: #E2E2E2;
                        border-bottom: 1px #C1C1C2 solid; 
                        color: #201F20;
                        margin: 0;
                        font-weight: normal;
                    }

                    /* Header2 style, used for "Overview" and other sections */
                    h2
                    {
                        font-size: 18pt;
                        font-weight: normal;
                        padding: 15px 0 5px 0;
                        margin: 0;
                    }

                    /* Header3 style, used for sub-sections, such as project name */
                    h3
                    {
                        font-weight: normal;
                        font-size: 15pt;
                        margin: 0;
                        padding: 15px 0 5px 0;
                        background-color: transparent;
                    }

                    /* Color all hyperlinks one color */
                    a
                    {
                        color: #1382CE;
                    }

                    /* Table styles */ 
                    table
                    {
                        border-spacing: 0 0;
                        border-collapse: collapse;
                        font-size: 10pt;
                    }

                    table th
                    {
                        background: #E7E7E8;
                        text-align: left;
                        text-decoration: none;
                        font-weight: normal;
                        padding: 3px 6px 3px 6px;
                    }

                    table td
                    {
                        vertical-align: top;
                        padding: 3px 6px 5px 5px;
                        margin: 0px;
                        border: 1px solid #E7E7E8;
                        background: #F7F7F8;
                    }

                    /* Local link is a style for hyperlinks that link to file:/// content, there are lots so color them as 'normal' text until the user mouse overs */
                    .localLink
                    {
                        color: #1E1E1F;
                        background: #EEEEED;
                        text-decoration: none;
                    }

                    .localLink:hover
                    {
                        color: #1382CE;
                        background: #FFFF99;
                        text-decoration: none;
                    }

                    /* Center text, used in the over views cells that contain message level counts */ 
                    .textCentered
                    {
                        text-align: center;
                    }

                    /* The message cells in message tables should take up all avaliable space */
                    .messageCell
                    {
                        width: 100%;
                    }

                    /* Padding around the content after the h1 */ 
                    #content 
                    {
	                    padding: 0px 12px 12px 12px; 
                    }

                    /* The overview table expands to width, with a max width of 97% */ 
                    #overview table
                    {
                        width: auto;
                        max-width: 75%; 
                    }

                    /* The messages tables are always 97% width */
                    #messages table
                    {
                        width: 97%;
                    }

                    /* All Icons */
                    .IconSuccessEncoded, .IconInfoEncoded, .IconWarningEncoded, .IconErrorEncoded
                    {
                        min-width:18px;
                        min-height:18px; 
                        background-repeat:no-repeat;
                        background-position:center;
                    }

                    /* Success icon encoded */
                    .IconSuccessEncoded
                    {
                        /* Note: Do not delete the comment below. It is used to verify the correctness of the encoded image resource below before the product is released */
                        /* [---XsltValidateInternal-Base64EncodedImage:IconSuccess#Begin#background-image: url(data:image/png;base64,#Separator#);#End#] */
                        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABcElEQVR4Xq2TsUsCURzHv15g8ZJcBWlyiYYgCIWcb9DFRRwMW5TA2c0/QEFwFkxxUQdxVlBwCYWOi6IhWgQhBLHJUCkhLr/BW8S7gvrAg+N+v8/v+x68Z8MGy+XSCyABQAXgBgHGALoASkIIDWSLeLBetdHryMjd5IxQPWT4rn1c/P7+xxp72Cs9m5SZ0Bq2vPnbPFafK2zDvmNHypdC0BPkLlQhxJsCAhQoZwdZU5mwxh720qGo8MzTxTTKZDPCx2HoVzp6lz0Q9tKhyx0kGs8Ny+TkWRKk8lCROwEduhyg9l/6lunOPSfmH3NUH6uQ0KHLAe7JYvJjevm+DAMGJHToKtigE+vwvIidxLamb8IBY9e+C5LiXREkfho3TSd06HJA13/oh6T51MTsfQbHrsMynQ5dDihFjiK8JJAU9AKIWTp76dCVN7HWHrajmUEGvyF9nkbAE6gLIS7kTUyuf2gscLoJrElZo/Mvj+nPz/kLTmfnEwP3tB0AAAAASUVORK5CYII=);
                    }

                    /* Information icon encoded */
                    .IconInfoEncoded
                    {
                        /* Note: Do not delete the comment below. It is used to verify the correctness of the encoded image resource below before the product is released */
                        /* [---XsltValidateInternal-Base64EncodedImage:IconInformation#Begin#background-image: url(data:image/png;base64,#Separator#);#End#] */
                        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHElEQVR4Xs2TsUoDQRRF7wwoziokjZUKadInhdhukR9YP8DMX1hYW+QvdsXa/QHBbcXC7W0CamWTQnclFutceIQJwwaWNLlwm5k5d94M76mmaeCrrmsLYOocY12FcxZFUeozCqKqqgYA8uevv1H6VuPxcwlfk5N92KHBxfFeCSAxxswlYAW/Xr989x/mv9gkhtyMDhcAxgzRsp7flj8B/HF1RsMXq+NZMkopaHe7lbKxQUEIGbKsYNoGn969060hZBkQex/W8oRQwsQaW2o3Ago2SVcJUzAgY3N0lTCZZm+zPS8HB51gMmS1DEYyOz9acKO1D8JWTlafKIMxdhvlfdyT94Vv5h7P8Ky7nQzACmhvKq3zk3PjW9asz9D/1oigecsioooAAAAASUVORK5CYII=);
                    }

                    /* Warning icon encoded */
                    .IconWarningEncoded
                    {
                        /* Note: Do not delete the comment below. It is used to verify the correctness of the encoded image resource below before the product is released */
                        /* [---XsltValidateInternal-Base64EncodedImage:IconWarning#Begin#background-image: url(data:image/png;base64,#Separator#);#End#] */
                        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAx0lEQVR4XpWSMQ7CMAxFf4xAyBMLCxMrO8dhaBcuwdCJS3RJBw7SA/QGTCxdWJgiQYWKXJWKIXHIlyw5lqr34tQgEOdcBsCOx5yZK3hCCKdYXneQkh4pEfqzLfu+wVDSyyzFoJjfz9NB+pAF+eizx2Vruts0k15mPgvS6GYvpVtQhB61IB/dk6AF6fS4Ben0uIX5odtFe8Q/eW1KvFeH4e8khT6+gm5B+t3juyDt7n0jpe+CANTd+oTUjN/U3yVaABnSUjFz/gFq44JaVSCXeQAAAABJRU5ErkJggg==);
                    }

                    /* Error icon encoded */
                    .IconErrorEncoded
                    {
                        /* Note: Do not delete the comment below. It is used to verify the correctness of the encoded image resource below before the product is released */
                        /* [---XsltValidateInternal-Base64EncodedImage:IconError#Begin#background-image: url(data:image/png;base64,#Separator#);#End#] */
                        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABQElEQVR4XqWTvUoEQRCE6wYPZUA80AfwAQz23uCMjA7MDRQEIzPBVEyNTQUFIw00vcQTTMzuAh/AxEQQT8HF/3G/oGGnEUGuoNnd6qoZuqltyKEsyzVJq5I6rnUp6SjGeGhESikzzlc1eL7opfuVbrqbU1Zw9NCgtQMaZpY0eNnaaL2fHusvTK5vKu7sjSS1Y4y3QUA6K3e3Mau5UFDyMP7tYF9o8cAHZv68vipoIJg971PZIZ5HiwdvYGGvFVFHmGmZ2MxwmQYPXubPl9Up0tfoMQGetXd6mRbvhBw+boZ6WF7Mbv1+GsHRk0fQmPAH1GfmZirbCfDJ61tw3Px8/8pZsPAG4jlVhcPgZ7adwNWBB68lkRQWFiTgFlbnLY3DGGM7izIJIyT/jjIvEJw6fdJTc6krDzh6aMwMP9bvDH4ADSsa9uSWVJkAAAAASUVORK5CYII=);
                    }
                 </style><script type="text/javascript" language="javascript"> 
          
            // Startup 
            // Hook up the the loaded event for the document/window, to linkify the document content
            var startupFunction = function() { linkifyElement("messages"); };
            
            if(window.attachEvent)
            {
              window.attachEvent('onload', startupFunction);
            }
            else if (window.addEventListener) 
            {
              window.addEventListener('load', startupFunction, false);
            }
            else 
            {
              document.addEventListener('load', startupFunction, false);
            } 
            
            // Toggles the visibility of table rows with the specified name 
            function toggleTableRowsByName(name)
            {
               var allRows = document.getElementsByTagName('tr');
               for (i=0; i < allRows.length; i++)
               {
                  var currentName = allRows[i].getAttribute('name');
                  if(!!currentName && currentName.indexOf(name) == 0)
                  {
                      var isVisible = allRows[i].style.display == ''; 
                      isVisible ? allRows[i].style.display = 'none' : allRows[i].style.display = '';
                  }
               }
            }
            
            function scrollToFirstVisibleRow(name) 
            {
               var allRows = document.getElementsByTagName('tr');
               for (i=0; i < allRows.length; i++)
               {
                  var currentName = allRows[i].getAttribute('name');
                  var isVisible = allRows[i].style.display == ''; 
                  if(!!currentName && currentName.indexOf(name) == 0 && isVisible)
                  {
                     allRows[i].scrollIntoView(true); 
                     return true; 
                  }
               }
               
               return false;
            }
            
            // Linkifies the specified text content, replaces candidate links with html links 
            function linkify(text)
            {
                 if(!text || 0 === text.length)
                 {
                     return text; 
                 }

                 // Find http, https and ftp links and replace them with hyper links 
                 var urlLink = /(http|https|ftp)\:\/\/[a-zA-Z0-9\-\.]+(:[a-zA-Z0-9]*)?\/?([a-zA-Z0-9\-\._\?\,\/\\\+&%\$#\=~;\{\}])*/gi;
                 
                 return text.replace(urlLink, '<a href="$&">$&</a>') ;
            }
            
            // Linkifies the specified element by ID
            function linkifyElement(id)
            {
                var element = document.getElementById(id);
                if(!!element)
                {
                  element.innerHTML = linkify(element.innerHTML); 
                }
            }
            
            function ToggleMessageVisibility(projectName)
            {
              if(!projectName || 0 === projectName.length)
              {
                return; 
              }
              
              toggleTableRowsByName("MessageRowClass" + projectName);
              toggleTableRowsByName('MessageRowHeaderShow' + projectName);
              toggleTableRowsByName('MessageRowHeaderHide' + projectName); 
            }
            
            function ScrollToFirstVisibleMessage(projectName)
            {
              if(!projectName || 0 === projectName.length)
              {
                return; 
              }
              
              // First try the 'Show messages' row
              if(!scrollToFirstVisibleRow('MessageRowHeaderShow' + projectName))
              {
                // Failed to find a visible row for 'Show messages', try an actual message row 
                scrollToFirstVisibleRow('MessageRowClass' + projectName); 
              }
            }
           </script></head><body><h1 _locID="ConversionReport">
          Migration Report - </h1><div id="content"><h2 _locID="OverviewTitle">Overview</h2><div id="overview"><table><tr><th></th><th _locID="ProjectTableHeader">Project</th><th _locID="PathTableHeader">Path</th><th _locID="ErrorsTableHeader">Errors</th><th _locID="WarningsTableHeader">Warnings</th><th _locID="MessagesTableHeader">Messages</th></tr><tr><td class="IconErrorEncoded" /><td><strong><a href="#Uncrustify">Uncrustify</a></strong></td><td>Uncrustify_Win32_2011.vcxproj</td><td class="textCentered"><a href="#UncrustifyError">1</a></td><td class="textCentered"><a>0</a></td><td class="textCentered"><a href="#">0</a></td></tr><tr><td class="IconSuccessEncoded" /><td><strong><a href="#Solution"><span _locID="OverviewSolutionSpan">Solution</span></a></strong></td><td>Uncrustify_Win32_2011.sln</td><td class="textCentered"><a>0</a></td><td class="textCentered"><a>0</a></td><td class="textCentered"><a href="#" onclick="ScrollToFirstVisibleMessage('Solution'); return false;">1</a></td></tr></table></div><h2 _locID="SolutionAndProjectsTitle">Solution and projects</h2><div id="messages"><a name="Uncrustify" /><h3>Uncrustify</h3><table><tr id="UncrustifyHeaderRow"><th></th><th class="messageCell" _locID="MessageTableHeader">Message</th></tr><tr name="ErrorRowClassUncrustify"><td class="IconErrorEncoded"><a name="UncrustifyError" /></td><td class="messageCell"><strong>Uncrustify_Win32_2011.vcxproj:
        </strong><span>The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=500718&amp;projecttype=8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942</span></td></tr></table><a name="Solution" /><h3 _locID="ProjectDisplayNameHeader">Solution</h3><table><tr id="SolutionHeaderRow"><th></th><th class="messageCell" _locID="MessageTableHeader">Message</th></tr><tr name="MessageRowHeaderShowSolution"><td class="IconInfoEncoded" /><td class="messageCell"><a _locID="ShowAdditionalMessages" href="#" name="SolutionMessage" onclick="ToggleMessageVisibility('Solution'); return false;">
          Show 1 additional messages
        </a></td></tr><tr name="MessageRowClassSolution" style="display: none"><td class="IconInfoEncoded"><a name="SolutionMessage" /></td><td class="messageCell"><strong>Uncrustify_Win32_2011.sln:
        </strong><span>The solution file does not require migration.</span></td></tr><tr style="display: none" name="MessageRowHeaderHideSolution"><td class="IconInfoEncoded" /><td class="messageCell"><a _locID="HideAdditionalMessages" href="#" name="SolutionMessage" onclick="ToggleMessageVisibility('Solution'); return false;">
          Hide 1 additional messages
        </a></td></tr></table></div></div></body></html>

**Comment by spiked3** [comment]
well that didnt work well, and I cant post zips. 
![untitled-1](https://cloud.githubusercontent.com/assets/2166286/8757542/ecde899e-2c8f-11e5-94fb-293aeb1bd5de.gif)

**Comment by dirk-thomas** [comment]
The error link points to VS 2013 documentation and says that it couldn't find the right project type. Do you have Visual C++ installed? Do you also have VS 2013 installed beside VS 2015?

**Comment by spiked3** [comment]
I have vs2013 and vs 2015, but I have been having trouble with c++ in vs2015.  Is that the first c++ program in the build?  It ran for quite a while before it got there.

**Comment by dirk-thomas** [comment]
Yes, that is the first C++ program in the build. You should make sure to only have VS 2015 in the environment and that the build is actually using VS 2015. Especially the following packages won't compile with VS 2013 anyway.

**Comment by spiked3** [comment]
I definitely have vs 2015 installed - about 10 times in the last 3 days trying to resolve another c++ problem with it.  So it is probably my compiler. sigh.  Ok, I will dig more into it on this end.

**Comment by spiked3** [comment]
I finally got vs 2015 straightened out (I hope for good) and it did make it past this.
It is now failing @geometry_interfaces - will look to see if that is the same point as your build system.
But you can close this one for good. Thanks for your help.

**Comment by dirk-thomas** [comment]
Thanks for digging into it.
