### ISSUE TITLE
Is TODO still relevant ?

### ISSUE THREAD

**Issue by ahcorde** [ros2/examples#387]
I can see a TODO in some of the examples. @clalancette Is this comment still relevant ?

// TODO(jacobperron): Remove this once it is included as part of 'rclcpp.hpp'

**Comment by clalancette** [comment]
Honestly, I don't think so.  There was some talk at one point about having `rclcpp/rclcpp.hpp` also include `rclcpp_action/rclcpp_action.hpp`, but I honestly don't see how that could happen.  As it stands, `rclcpp_action` depends on `rclcpp`, so it would end up being a circular dependency.

So yeah, I'd approve a PR which removed those comments.

**Comment by ahcorde** [comment]
https://github.com/ros2/examples/pull/388

**Comment by ahcorde** [comment]
https://github.com/ros2/demos/pull/699
