### ISSUE TITLE
consolidate development guidelines and policy documents

### ISSUE THREAD

**Issue by tfoote** [ros2/examples#50]
We have two parallel docs: https://github.com/ros2/design/wiki/Development-Policies and https://github.com/ros2/examples/wiki/Development-guidelines

Capturing this from the email thread.

**Comment by gerkey** [comment]
I put the consolidated content here: https://github.com/ros2/ros2/wiki/Developer-Guide, with pointers from the previous pages.

I did my best to remove or at least tag (e.g., *planned; not used yet*) stuff that's not really in place right now.  We might need more changes in the C++ style section, but I don't know what needs to be changed there.
