### ISSUE TITLE
Verify that the rmw implementation matches executable

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/examples#96]
@dhood will work on making sure the name of the executable actually matches the middleware implementation.

**Comment by wjwwood** [comment]
@dhood I just re-reviewed all the associated PR's. I'd say, run one more set of CI on it (just to make sure something weird didn't happen) and if they pass merge them. Thanks for working on it!

**Comment by dhood** [comment]
yep it's already running now thanks!

**Comment by dhood** [comment]
http://ci.ros2.org/job/ci_osx/1044/ (no failures)
http://ci.ros2.org/job/ci_windows/1348/ (failures with age >= 1)
http://ci.ros2.org/job/ci_linux/1323/ (no failures)

merging these prs now
